"""Render publication digests as HTML emails using Jinja2."""

from __future__ import annotations

from datetime import date

from jinja2 import Environment, BaseLoader

from bmnews.db.models import Publication, PublicationScore

# ---------------------------------------------------------------------------
# HTML email template
# ---------------------------------------------------------------------------

_TEMPLATE_SOURCE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BioMedical News Digest</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; background: #f5f5f5; color: #333; }
  .container { max-width: 700px; margin: 0 auto; background: #fff; }
  .header { background: #1a5276; color: #fff; padding: 24px 32px; }
  .header h1 { margin: 0; font-size: 22px; font-weight: 600; }
  .header .date { font-size: 14px; opacity: 0.85; margin-top: 4px; }
  .summary { padding: 16px 32px; background: #eaf2f8; font-size: 14px; color: #555; }
  .paper { padding: 20px 32px; border-bottom: 1px solid #eee; }
  .paper:last-child { border-bottom: none; }
  .paper h2 { font-size: 16px; margin: 0 0 6px; }
  .paper h2 a { color: #1a5276; text-decoration: none; }
  .paper h2 a:hover { text-decoration: underline; }
  .meta { font-size: 12px; color: #888; margin-bottom: 8px; }
  .scores { display: inline-block; font-size: 11px; margin-bottom: 8px; }
  .scores span { display: inline-block; padding: 2px 8px; border-radius: 10px; margin-right: 6px; }
  .relevance { background: #d5f5e3; color: #1e8449; }
  .quality { background: #d6eaf8; color: #2471a3; }
  .abstract { font-size: 13px; line-height: 1.5; color: #444; }
  .footer { padding: 16px 32px; font-size: 12px; color: #aaa; text-align: center; border-top: 1px solid #eee; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>BioMedical News Digest</h1>
    <div class="date">{{ digest_date }}</div>
  </div>
  <div class="summary">
    {{ papers | length }} publication{{ 's' if papers | length != 1 else '' }} matching your interests
  </div>
  {% for paper, score in papers %}
  <div class="paper">
    <h2><a href="{{ paper.url or '#' }}">{{ paper.title }}</a></h2>
    <div class="meta">
      {{ paper.authors[:5] | join(', ') }}{% if paper.authors | length > 5 %} et al.{% endif %}
      &middot; {{ paper.source }}
      {% if paper.published_date %}&middot; {{ paper.published_date }}{% endif %}
      {% if paper.doi %}&middot; <a href="https://doi.org/{{ paper.doi }}" style="color:#888">{{ paper.doi }}</a>{% endif %}
    </div>
    <div class="scores">
      <span class="relevance">Relevance {{ '%d' | format(score.relevance_score * 100) }}%</span>
      <span class="quality">Quality {{ '%d' | format(score.quality_score * 100) }}%</span>
    </div>
    {% if paper.abstract %}
    <div class="abstract">{{ paper.abstract[:500] }}{% if paper.abstract | length > 500 %}&hellip;{% endif %}</div>
    {% endif %}
  </div>
  {% endfor %}
  <div class="footer">
    Generated by <strong>BioMedical News</strong> &mdash; an open-source preprint discovery tool.
  </div>
</div>
</body>
</html>
"""

# Plain-text fallback
_TEXT_TEMPLATE_SOURCE = """\
BIOMEDICAL NEWS DIGEST — {{ digest_date }}
{{ '=' * 50 }}

{{ papers | length }} publication{{ 's' if papers | length != 1 else '' }} matching your interests

{% for paper, score in papers %}
{{ loop.index }}. {{ paper.title }}
   Authors: {{ paper.authors[:5] | join(', ') }}{% if paper.authors | length > 5 %} et al.{% endif %}

   Source: {{ paper.source }}  Published: {{ paper.published_date or 'N/A' }}
   Relevance: {{ '%d' | format(score.relevance_score * 100) }}%  Quality: {{ '%d' | format(score.quality_score * 100) }}%
   Link: {{ paper.url or 'N/A' }}
   {% if paper.doi %}DOI: https://doi.org/{{ paper.doi }}{% endif %}

   {{ (paper.abstract or '')[:400] }}{% if (paper.abstract or '') | length > 400 %}...{% endif %}

{% endfor %}
---
Generated by BioMedical News
"""

_env = Environment(loader=BaseLoader(), autoescape=True)
_html_template = _env.from_string(_TEMPLATE_SOURCE)

_text_env = Environment(loader=BaseLoader(), autoescape=False)
_text_template = _text_env.from_string(_TEXT_TEMPLATE_SOURCE)


def render_html(papers: list[tuple[Publication, PublicationScore]]) -> str:
    """Render the digest as an HTML string."""
    return _html_template.render(
        papers=papers,
        digest_date=date.today().strftime("%B %d, %Y"),
    )


def render_text(papers: list[tuple[Publication, PublicationScore]]) -> str:
    """Render the digest as plain text."""
    return _text_template.render(
        papers=papers,
        digest_date=date.today().strftime("%B %d, %Y"),
    )
